In [1]:
import numpy as np
import pandas as pd

In [2]:
from tensorflow.keras import datasets

In [3]:
(x_train, y_train), (x_test, y_test) = datasets.mnist.load_data()

In [4]:
y_train

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [5]:
x_train.shape

(60000, 28, 28)

In [6]:
x_test.shape

(10000, 28, 28)

In [7]:
width, height = 28, 28
input_shape = (width, height, 1)

In [8]:
input_shape

(28, 28, 1)

In [9]:
x_train = x_train.reshape(x_train.shape[0], height, width, 1)
x_test = x_test.reshape(x_test.shape[0], height, width, 1)

In [10]:
x_train = x_train.reshape(x_train.shape[0], height, width, 1)
x_test = x_test.reshape(x_test.shape[0], height, width, 1)

(60000, 28, 28, 1)

In [11]:
y_train.shape

(60000,)

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size = 0.1)

In [13]:
len(x_val)

6000

In [14]:
x_train = (x_train - x_train.mean()) / x_train.std()
x_val = (x_val - x_val.mean()) / x_val.std()
x_test = (x_test - x_test.mean()) / x_test.std()

In [15]:
x_train

array([[[[-0.42415712],
         [-0.42415712],
         [-0.42415712],
         ...,
         [-0.42415712],
         [-0.42415712],
         [-0.42415712]],

        [[-0.42415712],
         [-0.42415712],
         [-0.42415712],
         ...,
         [-0.42415712],
         [-0.42415712],
         [-0.42415712]],

        [[-0.42415712],
         [-0.42415712],
         [-0.42415712],
         ...,
         [-0.42415712],
         [-0.42415712],
         [-0.42415712]],

        ...,

        [[-0.42415712],
         [-0.42415712],
         [-0.42415712],
         ...,
         [-0.42415712],
         [-0.42415712],
         [-0.42415712]],

        [[-0.42415712],
         [-0.42415712],
         [-0.42415712],
         ...,
         [-0.42415712],
         [-0.42415712],
         [-0.42415712]],

        [[-0.42415712],
         [-0.42415712],
         [-0.42415712],
         ...,
         [-0.42415712],
         [-0.42415712],
         [-0.42415712]]],


       [[[-0.42415712],


In [16]:
from tensorflow import keras

In [17]:
num_labels = 10

y_train = keras.utils.to_categorical(y_train)

In [18]:
y_train

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [19]:
y_val = keras.utils.to_categorical(y_val)
y_test = keras.utils.to_categorical(y_test)

# Model

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, AveragePooling2D, Dropout, Flatten, Input, Conv2D, MaxPooling2D

In [21]:
model = Sequential()

model.add(Conv2D(6, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh', input_shape = (28, 28, 1)))
model.add(AveragePooling2D(pool_size = (2, 2), strides = (1, 1)))
model.add(Conv2D(16, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh'))
model.add(AveragePooling2D(pool_size = (2, 2), strides = (2, 2)))
model.add(Conv2D(120, kernel_size = (5, 5), strides = (1, 1), activation = 'tanh'))

model.add(Flatten())
model.add(Dense(84, activation = 'tanh'))
model.add(Dense(num_labels, activation = 'softmax'))

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [22]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d (Conv2D)                      │ (None, 24, 24, 6)           │             156 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d (AveragePooling2D) │ (None, 23, 23, 6)           │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_1 (Conv2D)                    │ (None, 19, 19, 16)          │           2,416 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ average_pooling2d_1                  │ (None, 9, 9, 16)            │               0 │
│ (AveragePooling2D)                   │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_2 (Conv2D)                    │ (None, 5, 5, 120)           │          48,120 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten (Flatten)                    │ (None, 3000)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 84)                  │         252,084 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 10)                  │             850 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 303,626 (1.16 MB)

 Trainable params: 303,626 (1.16 MB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.compile(loss = keras.losses.categorical_crossentropy, optimizer = 'adam', metrics = ['accuracy'])

In [26]:
history = model.fit(x_train, y_train, batch_size = 32, epochs = 10, verbose = 1, validation_data = (x_val, y_val))

Epoch 1/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 66s 37ms/step - accuracy: 0.9040 - loss: 0.3191 - val_accuracy: 0.9685 - val_loss: 0.1044
Epoch 2/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 62s 37ms/step - accuracy: 0.9703 - loss: 0.0950 - val_accuracy: 0.9747 - val_loss: 0.0853
Epoch 3/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 62s 37ms/step - accuracy: 0.9735 - loss: 0.0877 - val_accuracy: 0.9755 - val_loss: 0.0734
Epoch 4/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 67s 40ms/step - accuracy: 0.9779 - loss: 0.0740 - val_accuracy: 0.9755 - val_loss: 0.0734
Epoch 5/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 76s 36ms/step - accuracy: 0.9796 - loss: 0.0678 - val_accuracy: 0.9772 - val_loss: 0.0743
Epoch 6/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 56s 33ms/step - accuracy: 0.9809 - loss: 0.0623 - val_accuracy: 0.9768 - val_loss: 0.0726
Epoch 7/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 49s 29ms/step - accuracy: 0.9818 - loss: 0.0595 - val_accuracy: 0.9795 - val_loss: 0.0651
Epoch 8/10
1688/1688 ━━━━━━━━━━━━━━━━━━━━ 48s 28ms/step - accuracy: 0.9836 -

In [27]:
score = model.evaluate(x_test, y_test, verbose = 1)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.9810 - loss: 0.0534


In [28]:
score

[0.04578394442796707, 0.9850000143051147]